// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mocks -source=contract.go -destination=mocks/contract.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	session "iam/internal/domain/session"
	dto "iam/internal/usecase/account/dto"
	dto0 "iam/internal/usecase/session/dto"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetCurrentSession mocks base method.
func (m *MockUsecase) GetCurrentSession(ctx context.Context, request dto0.GetCurrentSessionIn) (*dto0.GetCurrentSessionOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentSession", ctx, request)
	ret0, _ := ret[0].(*dto0.GetCurrentSessionOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentSession indicates an expected call of GetCurrentSession.
func (mr *MockUsecaseMockRecorder) GetCurrentSession(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentSession", reflect.TypeOf((*MockUsecase)(nil).GetCurrentSession), ctx, request)
}

// Logout mocks base method.
func (m *MockUsecase) Logout(ctx context.Context, request dto0.LogoutIn) (*dto0.LogoutOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, request)
	ret0, _ := ret[0].(*dto0.LogoutOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockUsecaseMockRecorder) Logout(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockUsecase)(nil).Logout), ctx, request)
}

// Refresh mocks base method.
func (m *MockUsecase) Refresh(ctx context.Context, request dto0.RefreshIn) (*dto0.RefreshOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, request)
	ret0, _ := ret[0].(*dto0.RefreshOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockUsecaseMockRecorder) Refresh(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockUsecase)(nil).Refresh), ctx, request)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, accountID int64, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, accountID, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, accountID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, accountID, ttl)
}

// Delete mocks base method.
func (m *MockSessionRepository) Delete(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepositoryMockRecorder) Delete(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepository)(nil).Delete), ctx, sessionID)
}

// Get mocks base method.
func (m *MockSessionRepository) Get(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionRepositoryMockRecorder) Get(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionRepository)(nil).Get), ctx, sessionID)
}

// MockRefreshSessionRepository is a mock of RefreshSessionRepository interface.
type MockRefreshSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshSessionRepositoryMockRecorder
}

// MockRefreshSessionRepositoryMockRecorder is the mock recorder for MockRefreshSessionRepository.
type MockRefreshSessionRepositoryMockRecorder struct {
	mock *MockRefreshSessionRepository
}

// NewMockRefreshSessionRepository creates a new mock instance.
func NewMockRefreshSessionRepository(ctrl *gomock.Controller) *MockRefreshSessionRepository {
	mock := &MockRefreshSessionRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshSessionRepository) EXPECT() *MockRefreshSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshSessionRepository) Create(ctx context.Context, session session.RefreshSession) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRefreshSessionRepositoryMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshSessionRepository)(nil).Create), ctx, session)
}

// LoadByTokenHash mocks base method.
func (m *MockRefreshSessionRepository) LoadByTokenHash(ctx context.Context, tokenHash string) (*session.RefreshSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*session.RefreshSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByTokenHash indicates an expected call of LoadByTokenHash.
func (mr *MockRefreshSessionRepositoryMockRecorder) LoadByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByTokenHash", reflect.TypeOf((*MockRefreshSessionRepository)(nil).LoadByTokenHash), ctx, tokenHash)
}

// MarkUsed mocks base method.
func (m *MockRefreshSessionRepository) MarkUsed(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockRefreshSessionRepositoryMockRecorder) MarkUsed(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockRefreshSessionRepository)(nil).MarkUsed), ctx, sessionID)
}

// Revoke mocks base method.
func (m *MockRefreshSessionRepository) Revoke(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshSessionRepositoryMockRecorder) Revoke(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshSessionRepository)(nil).Revoke), ctx, sessionID)
}

// RevokeFamily mocks base method.
func (m *MockRefreshSessionRepository) RevokeFamily(ctx context.Context, familyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeFamily", ctx, familyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeFamily indicates an expected call of RevokeFamily.
func (mr *MockRefreshSessionRepositoryMockRecorder) RevokeFamily(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeFamily", reflect.TypeOf((*MockRefreshSessionRepository)(nil).RevokeFamily), ctx, familyID)
}

// MockAccountUsecase is a mock of AccountUsecase interface.
type MockAccountUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAccountUsecaseMockRecorder
}

// MockAccountUsecaseMockRecorder is the mock recorder for MockAccountUsecase.
type MockAccountUsecaseMockRecorder struct {
	mock *MockAccountUsecase
}

// NewMockAccountUsecase creates a new mock instance.
func NewMockAccountUsecase(ctrl *gomock.Controller) *MockAccountUsecase {
	mock := &MockAccountUsecase{ctrl: ctrl}
	mock.recorder = &MockAccountUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountUsecase) EXPECT() *MockAccountUsecaseMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockAccountUsecase) GetByID(ctx context.Context, request dto.GetByIDIn) (*dto.GetByIDOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, request)
	ret0, _ := ret[0].(*dto.GetByIDOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountUsecaseMockRecorder) GetByID(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountUsecase)(nil).GetByID), ctx, request)
}
