// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mocks -source=contract.go -destination=mocks/contract.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	account "iam/internal/domain/account"
	session "iam/internal/domain/session"
	dto "iam/internal/usecase/account/dto"
	dto0 "iam/internal/usecase/oauth/dto"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ExchangeAuthCode mocks base method.
func (m *MockUsecase) ExchangeAuthCode(ctx context.Context, request dto0.ExchangeAuthCodeIn) (*dto0.ExchangeAuthCodeOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeAuthCode", ctx, request)
	ret0, _ := ret[0].(*dto0.ExchangeAuthCodeOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeAuthCode indicates an expected call of ExchangeAuthCode.
func (mr *MockUsecaseMockRecorder) ExchangeAuthCode(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeAuthCode", reflect.TypeOf((*MockUsecase)(nil).ExchangeAuthCode), ctx, request)
}

// HandleGoogleCallback mocks base method.
func (m *MockUsecase) HandleGoogleCallback(ctx context.Context, request dto0.HandleGoogleCallbackIn) (*dto0.HandleGoogleCallbackOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGoogleCallback", ctx, request)
	ret0, _ := ret[0].(*dto0.HandleGoogleCallbackOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGoogleCallback indicates an expected call of HandleGoogleCallback.
func (mr *MockUsecaseMockRecorder) HandleGoogleCallback(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGoogleCallback", reflect.TypeOf((*MockUsecase)(nil).HandleGoogleCallback), ctx, request)
}

// StartGoogleAuth mocks base method.
func (m *MockUsecase) StartGoogleAuth(ctx context.Context, request dto0.StartGoogleAuthIn) (*dto0.StartGoogleAuthOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartGoogleAuth", ctx, request)
	ret0, _ := ret[0].(*dto0.StartGoogleAuthOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartGoogleAuth indicates an expected call of StartGoogleAuth.
func (mr *MockUsecaseMockRecorder) StartGoogleAuth(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartGoogleAuth", reflect.TypeOf((*MockUsecase)(nil).StartGoogleAuth), ctx, request)
}

// MockStateRepository is a mock of StateRepository interface.
type MockStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStateRepositoryMockRecorder
}

// MockStateRepositoryMockRecorder is the mock recorder for MockStateRepository.
type MockStateRepositoryMockRecorder struct {
	mock *MockStateRepository
}

// NewMockStateRepository creates a new mock instance.
func NewMockStateRepository(ctrl *gomock.Controller) *MockStateRepository {
	mock := &MockStateRepository{ctrl: ctrl}
	mock.recorder = &MockStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateRepository) EXPECT() *MockStateRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockStateRepository) Consume(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockStateRepositoryMockRecorder) Consume(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockStateRepository)(nil).Consume), ctx, state)
}

// Generate mocks base method.
func (m *MockStateRepository) Generate(ctx context.Context, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockStateRepositoryMockRecorder) Generate(ctx, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockStateRepository)(nil).Generate), ctx, ttl)
}

// MockGoogleProvider is a mock of GoogleProvider interface.
type MockGoogleProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleProviderMockRecorder
}

// MockGoogleProviderMockRecorder is the mock recorder for MockGoogleProvider.
type MockGoogleProviderMockRecorder struct {
	mock *MockGoogleProvider
}

// NewMockGoogleProvider creates a new mock instance.
func NewMockGoogleProvider(ctrl *gomock.Controller) *MockGoogleProvider {
	mock := &MockGoogleProvider{ctrl: ctrl}
	mock.recorder = &MockGoogleProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleProvider) EXPECT() *MockGoogleProviderMockRecorder {
	return m.recorder
}

// ExchangeCode mocks base method.
func (m *MockGoogleProvider) ExchangeCode(ctx context.Context, code string) (account.GoogleIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code)
	ret0, _ := ret[0].(account.GoogleIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockGoogleProviderMockRecorder) ExchangeCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockGoogleProvider)(nil).ExchangeCode), ctx, code)
}

// MockAccountUsecase is a mock of AccountUsecase interface.
type MockAccountUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAccountUsecaseMockRecorder
}

// MockAccountUsecaseMockRecorder is the mock recorder for MockAccountUsecase.
type MockAccountUsecaseMockRecorder struct {
	mock *MockAccountUsecase
}

// NewMockAccountUsecase creates a new mock instance.
func NewMockAccountUsecase(ctrl *gomock.Controller) *MockAccountUsecase {
	mock := &MockAccountUsecase{ctrl: ctrl}
	mock.recorder = &MockAccountUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountUsecase) EXPECT() *MockAccountUsecaseMockRecorder {
	return m.recorder
}

// GetBuyIdentity mocks base method.
func (m *MockAccountUsecase) GetBuyIdentity(ctx context.Context, request dto.GetBuyIdentityIn) (*dto.GetBuyIdentityOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuyIdentity", ctx, request)
	ret0, _ := ret[0].(*dto.GetBuyIdentityOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuyIdentity indicates an expected call of GetBuyIdentity.
func (mr *MockAccountUsecaseMockRecorder) GetBuyIdentity(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuyIdentity", reflect.TypeOf((*MockAccountUsecase)(nil).GetBuyIdentity), ctx, request)
}

// MockAuthCodeRepository is a mock of AuthCodeRepository interface.
type MockAuthCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCodeRepositoryMockRecorder
}

// MockAuthCodeRepositoryMockRecorder is the mock recorder for MockAuthCodeRepository.
type MockAuthCodeRepositoryMockRecorder struct {
	mock *MockAuthCodeRepository
}

// NewMockAuthCodeRepository creates a new mock instance.
func NewMockAuthCodeRepository(ctrl *gomock.Controller) *MockAuthCodeRepository {
	mock := &MockAuthCodeRepository{ctrl: ctrl}
	mock.recorder = &MockAuthCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCodeRepository) EXPECT() *MockAuthCodeRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockAuthCodeRepository) Consume(ctx context.Context, code string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, code)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockAuthCodeRepositoryMockRecorder) Consume(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockAuthCodeRepository)(nil).Consume), ctx, code)
}

// Generate mocks base method.
func (m *MockAuthCodeRepository) Generate(ctx context.Context, accountID int64, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, accountID, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockAuthCodeRepositoryMockRecorder) Generate(ctx, accountID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockAuthCodeRepository)(nil).Generate), ctx, accountID, ttl)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, accountID int64, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, accountID, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, accountID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, accountID, ttl)
}

// MockRefreshSessionRepository is a mock of RefreshSessionRepository interface.
type MockRefreshSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshSessionRepositoryMockRecorder
}

// MockRefreshSessionRepositoryMockRecorder is the mock recorder for MockRefreshSessionRepository.
type MockRefreshSessionRepositoryMockRecorder struct {
	mock *MockRefreshSessionRepository
}

// NewMockRefreshSessionRepository creates a new mock instance.
func NewMockRefreshSessionRepository(ctrl *gomock.Controller) *MockRefreshSessionRepository {
	mock := &MockRefreshSessionRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshSessionRepository) EXPECT() *MockRefreshSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshSessionRepository) Create(ctx context.Context, session session.RefreshSession) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRefreshSessionRepositoryMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshSessionRepository)(nil).Create), ctx, session)
}
