// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mocks -source=contract.go -destination=mocks/contract.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	account "iam/internal/domain/account"
	dto "iam/internal/usecase/account/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetBuyIdentity mocks base method.
func (m *MockUsecase) GetBuyIdentity(ctx context.Context, request dto.GetBuyIdentityIn) (*dto.GetBuyIdentityOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuyIdentity", ctx, request)
	ret0, _ := ret[0].(*dto.GetBuyIdentityOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuyIdentity indicates an expected call of GetBuyIdentity.
func (mr *MockUsecaseMockRecorder) GetBuyIdentity(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuyIdentity", reflect.TypeOf((*MockUsecase)(nil).GetBuyIdentity), ctx, request)
}

// GetByID mocks base method.
func (m *MockUsecase) GetByID(ctx context.Context, request dto.GetByIDIn) (*dto.GetByIDOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, request)
	ret0, _ := ret[0].(*dto.GetByIDOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsecaseMockRecorder) GetByID(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsecase)(nil).GetByID), ctx, request)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, identity account.GoogleIdentity) (account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, identity)
	ret0, _ := ret[0].(account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, identity)
}

// FindByGoogleSub mocks base method.
func (m *MockRepository) FindByGoogleSub(ctx context.Context, googleSub string) (account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGoogleSub", ctx, googleSub)
	ret0, _ := ret[0].(account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGoogleSub indicates an expected call of FindByGoogleSub.
func (mr *MockRepositoryMockRecorder) FindByGoogleSub(ctx, googleSub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGoogleSub", reflect.TypeOf((*MockRepository)(nil).FindByGoogleSub), ctx, googleSub)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id int64) (account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}
